[general]
library_name = "liblua"
output_file_path = "../src/capi.jl"
module_name = "C"
jll_pkg_name = "Lua_jll"
print_using_CEnum = false
prologue_file_path = "./prologue.jl"
output_ignorelist = [
    "LUA_VERSION",
    "LUA_RELEASE",
    "LUA_VDIR",
    "LUA_SHRDIR",
    "LUA_INTEGER_FMT",
    "LUA_VERSUFFIX",
    "LUA_COPYRIGHT",
    "LUA_API",
    "LUA_MININTEGER",
    "LUA_MAXINTEGER",
    "LUA_MAXUNSIGNED",
    "LUA_KCONTEXT",
    "LUAI_MAXALIGN",
    "LUALIB_API",
    "LUAMOD_API",
]

[codegen]
use_julia_bool = true
use_ccall_macro = true
opaque_func_arg_as_PtrCvoid = true